swagger: "2.0"
info:
  version: "1.0.0"
  title: "FIBranch-sandbox"
host: "v9rpn2j1d3.execute-api.us-east-1.amazonaws.com"
basePath: "/sandbox/esbapi/WealthManagement/FIBranch/V1_0/"
schemes:
- "https"
paths:
  /esbapi/creditCard/creditCardUtility/v2/getBINRanges:
    get:
      tags:
      - "getFITransitDetail"
      summary: "Get Branch  information"
      description: ""
      operationId: "getFITransitDetail"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "bmo-request-id"
        required: true
        type: "string"
      - in: "header"
        name: "x-api-key"
        required: true
        type: "string"
      - in: "path"
        name: "paginationInfo"
        schema:
          $ref: "#/definitions/paginationInfo"
        required: false
      - in: "body"
        name: "getFITransitDetailRequest"
        required: true
        schema:
          $ref: "#/definitions/getFITransitDetailRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/SuccessResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            x-request-id:
              type: "string"
            x-client-id:
              type: "string"
            x-refresh-token:
              type: "string"
            x-access-token:
              type: "string"      
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/response"
          headers:
            x-request-id:
              type: "string"
        500:
          description: "500 response"
          schema:
            $ref: "#/definitions/response"
          headers:
            x-request-id:
              type: "string"
        503:
          description: "503 response"
          schema:
            $ref: "#/definitions/response"
          headers:
            x-request-id:
              type: "string"
        404:
          description: "404 response"
          schema:
            $ref: "#/definitions/response"
          headers:
            x-request-id:
              type: "string"
        504:
          description: "504 response"
          schema:
            $ref: "#/definitions/response"
          headers:
            x-request-id:
              type: "string"
      security:
      - api_key: []
  "/esbapi/WealthManagement/FIBranch/V1_0/getFIList":
    get:
      tags:
      - "getFIList"
      operationId: "getFIList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "bmo-request-id"
        in: "header"
        required: true
        type: "string"
      - name: "x-api-key"
        in: "header"
        required: true
        type: "string"
      - in: path
        name: userId
        schema:
          $ref: "#/definitions/paginationInfo"
        required: false
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/SuccessResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            x-request-id:
              type: "string"
            x-client-id:
              type: "string"
            x-refresh-token:
              type: "string"
            x-access-token:
              type: "string"
        400:
          description: "400 response"
          schema:
            $ref: "#/definitions/response"
          headers:
            x-request-id:
              type: "string"
        500:
          description: "500 response"
          schema:
            $ref: "#/definitions/response"
          headers:
            x-request-id:
              type: "string"
        503:
          description: "503 response"
          schema:
            $ref: "#/definitions/response"
          headers:
            x-request-id:
              type: "string"
        404:
          description: "404 response"
          schema:
            $ref: "#/definitions/response"
          headers:
            x-request-id:
              type: "string"
        504:
          description: "504 response"
          schema:
            $ref: "#/definitions/response"
          headers:
            x-request-id:
              type: "string"
      security:
                - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
    
definitions:
  getFITransitDetailRequest:
    type: "object"
    required:
    - "transitnumber"
    - "InstitutionNumber"
    properties:
      transitnumber:
        type: "string"
      InstitutionNumber:
        type: "string"
        
  paginationInfo:
    type: "object"
    required:
    - "ReturnAvailableResultCount"
    - "PageStartIndex"
    - "PageEndIndex"
    properties:
      ReturnAvailableResultCount:
        type: "string"
      PageStartIndex:
        type: "integer"
      PageEndIndex:
        type: "integer"
        
  SuccessResult:
    type: "object"
    required:
    - "code"
    - "messages"
    - "status"
    properties:
      code:
        type: "string"
        description: "Contains the API response code e.g. 200, 500 etc"
      status:
        type: "string"
        description: "Status e.g."
        enum:
        - "SUCCESS"
        - "PARTIAL"
        - "FAILURE"
      messages:
        type: "array"
        description: "Contains the response fault message i.e. 'Bad Request', 'Internal\
          \ Server Error' etc"
        items:
          type: "object"
          required:
          - "InstitutionNumber"
          properties:
            InstitutionNumber:
              type: "string"
            InstitutionType:
              type: "string"
            StatusIndicator:
              type: "string"
            CrossReferenceNumber:
              type: "string"
            LanguagePreferenceCode:
              type: "string"
            InstitutionNameFrench:
              type: "string"
            BranchDomicile:
              type: "string"
            CivicAddress:
              type: "string"
            PostalAddress:
              type: "string"
            TownCity:
              type: "string"
            ProvinceCode:
              type: "string"
            PostalCode:
              type: "string"
            Country:
              type: "string"
            InstIdentClearerCredits:
              type: "string"
            IndirectClearerMICREncodingData:
              type: "string"
            ServiceabilityCode:
              type: "string"
            ExchangePointNum:
              type: "string"
            ForeignBankTransitNumber:
              type: "string"
            EffectiveDate:
              type: "string"
  result:
    type: "object"
    required:
    - "code"
    - "messages"
    - "status"
    properties:
      code:
        type: "string"
        description: "Contains the API response code e.g. 200, 500 etc"
      status:
        type: "string"
        description: "Status e.g."
        enum:
        - "SUCCESS"
        - "PARTIAL"
        - "FAILURE"
      messages:
        type: "array"
        description: "Contains the response fault message i.e. 'Bad Request', 'Internal\
          \ Server Error' etc"
        items:
          type: "string"
          
  response:
    type: "object"
    required:
    - "result"
    properties:
      result:
        $ref: "#/definitions/result"
        
  SuccessResponse:
    type: "object"
    required:
    - "result"
    properties:
      result:
        $ref: "#/definitions/SuccessResult"
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
